#!/usr/bin/env python3
"""Run the unmodified EPC2204 LTspice model at datasheet table conditions.

This is the first Stage 1 baseline: vendor model -> LTspice adapter -> parsed
values compared with the datasheet's electrical-characteristics table. The
comparison rules below are fixed before any run:

* rows with datasheet min and/or max limits are reported as inside or outside
  those limits;
* typical-only rows get a model/typical ratio and are flagged for review when
  the ratio is outside 1 +/- SCREENING_BAND.  This is a screening aid chosen
  for the first baseline, not an acceptance tolerance.

Datasheet curves are also simulated and stored for the later digitized-curve
comparison. The model is never modified; it is checked against the SHA-256
recorded in devices/epc/sources.json before use.
"""
import argparse
from dataclasses import asdict
import hashlib
import json
import math
from pathlib import Path
import sys
import uuid
import zipfile

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from circuit_tools.ltspice import ltspice_capability, parse_raw, run_ltspice

VENDOR = ROOT / "vendor" / "epc"
SOURCES = ROOT / "devices" / "epc" / "sources.json"
LIB_NAME = "EPCGaNLibrary.lib"
SCREENING_BAND = 0.25
BVDSS_HALF = 50.0  # V; datasheet COSS(ER)/COSS(TR) are defined from 0 to 50% of BVDSS = 100 V

# Datasheet EPC2204, revised 26 November 2024, TJ = 25 C unless stated.
DATASHEET = {
    "rds_on":  {"unit": "ohm", "typ": 4.4e-3, "max": 6e-3, "conditions": "VGS = 5 V, ID = 16 A"},
    "vgs_th":  {"unit": "V", "min": 0.8, "typ": 1.1, "max": 2.5, "conditions": "VDS = VGS, ID = 4 mA"},
    "vsd":     {"unit": "V", "typ": 1.6, "conditions": "IS = 0.5 A, VGS = 0 V (defined by design)"},
    "ciss":    {"unit": "F", "typ": 644e-12, "max": 851e-12, "conditions": "VDS = 50 V, VGS = 0 V"},
    "crss":    {"unit": "F", "typ": 2.3e-12, "conditions": "VDS = 50 V, VGS = 0 V"},
    "coss":    {"unit": "F", "typ": 304e-12, "max": 456e-12, "conditions": "VDS = 50 V, VGS = 0 V"},
    "coss_er": {"unit": "F", "typ": 401e-12, "conditions": "VDS = 0 to 50 V, VGS = 0 V"},
    "coss_tr": {"unit": "F", "typ": 501e-12, "conditions": "VDS = 0 to 50 V, VGS = 0 V"},
    "qg":      {"unit": "C", "typ": 5.7e-9, "max": 7.4e-9, "conditions": "VDS = 50 V, VGS = 5 V, ID = 16 A"},
    "qgs":     {"unit": "C", "typ": 1.8e-9, "conditions": "VDS = 50 V, ID = 16 A"},
    "qgd":     {"unit": "C", "typ": 0.8e-9, "conditions": "VDS = 50 V, ID = 16 A"},
    "qg_th":   {"unit": "C", "typ": 1.0e-9, "conditions": "VDS = 50 V, ID = 16 A"},
    "qoss":    {"unit": "C", "typ": 25e-9, "max": 38e-9, "conditions": "VDS = 50 V, VGS = 0 V"},
}

AC_FREQ = 1e6  # Hz; Rg = 0.4 ohm makes the series-resistance error ~(w Rg C)^2 < 1e-5
GATE_CURRENT = 10e-3  # A, constant-current gate charge
HEAD = "* EPC2204 unmodified vendor model; bench generated by scripts/epc2204_baseline.py\n.lib EPCGaNLibrary.lib\n"


def benches():
    b = {}
    for t in (25, 125):
        b[f"rds_on_{t}C"] = HEAD + f"""* RDS(on): VGS = 5 V, 16 A forced into the drain
Vg g 0 5
Id 0 d 16
X1 g d 0 EPC2204
.temp {t}
.op
.end
"""
    b["vgs_th"] = HEAD + """* VGS(th): drain tied to gate, sweep until ID = 4 mA
Vg g 0 0
X1 g g 0 EPC2204
.temp 25
.dc Vg 0 3 1m
.end
"""
    b["vsd"] = HEAD + """* VSD: 0.5 A reverse conduction, VGS = 0 V
Vg g 0 0
Is d 0 0.5
X1 g d 0 EPC2204
.temp 25
.op
.end
"""
    b["caps_gate_ac"] = HEAD + f"""* CISS and CRSS: AC on gate, drain held at 50 V (AC ground)
Vg g 0 0 AC 1
Vd d 0 50
X1 g d 0 EPC2204
.temp 25
.ac list {AC_FREQ:g}
.end
"""
    b["coss_curve_ac"] = HEAD + f"""* COSS(VDS): AC on drain, gate and source AC-grounded, VDS stepped 0..100 V
.param vds=50
Vd d 0 {{vds}} AC 1
Vg g 0 0
X1 g d 0 EPC2204
.temp 25
.step param vds 0 100 0.25
.ac list {AC_FREQ:g}
.end
"""
    b["qoss_tran"] = HEAD + """* QOSS/EOSS: drain ramped 0 -> 50 V in 1 us, VGS = 0 V
Vd d 0 PWL(0 0 1u 50 1.5u 50)
Vg g 0 0
X1 g d 0 EPC2204
.temp 25
.options plotwinsize=0
.tran 0 1.5u 0 1n
.end
"""
    b["gate_charge_tran"] = HEAD + f"""* Gate charge: 50 V supply, 16 A load current with ideal clamp diode, {GATE_CURRENT*1e3:g} mA gate current
Vdd vdd 0 50
Il vdd d 16
Dc d vdd dclamp
.model dclamp D(Ron=1m Roff=1G Vfwd=0)
Ig 0 g PULSE(0 {GATE_CURRENT:g} 100n 1n 1n 5u 10u)
* Hold-down resistor: without it the floating gate settles near 2 V through the model's
* convergence resistors, above VGS(th). Charge is integrated from the gate terminal current.
Rhold g 0 100k
X1 g d 0 EPC2204
.temp 25
.options plotwinsize=0
.tran 0 1.5u 0 0.1n
.end
"""
    b["output_curves_25C"] = HEAD + """* Output characteristics (datasheet Fig. 1 axes): VDS 0..3 V, VGS 2..5 V
Vd d 0 0
Vg g 0 0
X1 g d 0 EPC2204
.temp 25
.dc Vd 0 3 10m Vg 2 5 1
.end
"""
    for t in (25, 125):
        b[f"transfer_curve_{t}C"] = HEAD + f"""* Transfer characteristic (datasheet Fig. 2 axes): VDS = 3 V
Vd d 0 3
Vg g 0 0
X1 g d 0 EPC2204
.temp {t}
.dc Vg 0 5 10m
.end
"""
    return b


def cross(xs, ys, level, start=0):
    """First linear-interpolated x where ys reaches level (either direction) after index start."""
    for i in range(max(start, 1), len(ys)):
        a, b = ys[i - 1] - level, ys[i] - level
        if a == 0:
            return xs[i - 1]
        if a * b < 0 or b == 0:
            return xs[i - 1] + (xs[i] - xs[i - 1]) * (-a) / (b - a)
    return None


def cumtrapz(xs, ys):
    out = [0.0]
    for i in range(1, len(xs)):
        out.append(out[-1] + 0.5 * (ys[i] + ys[i - 1]) * (xs[i] - xs[i - 1]))
    return out


def at(xs, ys, x):
    for i in range(1, len(xs)):
        if xs[i] >= x:
            return ys[i - 1] + (ys[i] - ys[i - 1]) * (x - xs[i - 1]) / (xs[i] - xs[i - 1])
    return None


def classify(name, value):
    row = dict(DATASHEET[name])
    row["model"] = value
    if value is None:
        row["outcome"] = "not-measured"
        return row
    if "typ" in row:
        row["ratio_to_typ"] = value / row["typ"]
    if "min" in row or "max" in row:
        inside = row.get("min", -math.inf) <= value <= row.get("max", math.inf)
        row["outcome"] = "inside-datasheet-limits" if inside else "outside-datasheet-limits"
    else:
        row["outcome"] = ("near-typical" if abs(row["ratio_to_typ"] - 1) <= SCREENING_BAND
                          else "review")
    return row


def library_path():
    sources = json.loads(SOURCES.read_text(encoding="utf-8"))
    entry = next(f for f in sources["files"] if f["name"] == "EPCGaNLibrary.zip")
    archive = VENDOR / "EPCGaNLibrary.zip"
    if not archive.is_file():
        raise SystemExit(f"missing {archive}; download it from {entry['url']} (see devices/epc/sources.json)")
    digest = hashlib.sha256(archive.read_bytes()).hexdigest()
    if digest != entry["sha256"]:
        raise SystemExit(f"{archive} sha256 {digest} does not match the recorded {entry['sha256']}")
    lib = VENDOR / "ltspice" / LIB_NAME
    lib.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(archive) as z:
        data = z.read(LIB_NAME)
    if not lib.is_file() or lib.read_bytes() != data:
        lib.write_bytes(data)
    return lib, digest


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--executable", default=None)
    parser.add_argument("--output", type=Path, default=ROOT / "results/gan/epc2204-baseline.json")
    parser.add_argument("--curves", type=Path, default=ROOT / "results/gan/epc2204-model-curves.json")
    args = parser.parse_args()
    lib, archive_sha = library_path()
    run_root = ROOT / "runs" / ("epc2204-baseline-" + uuid.uuid4().hex)
    runs, raws = {}, {}
    for name, text in benches().items():
        r = run_ltspice(text, run_root / name, libraries=[lib], executable=args.executable, timeout_s=300)
        runs[name] = r
        if r.status == "completed" and r.result_path:
            raws[name] = parse_raw(r.result_path)
    failed = {n: r.message for n, r in runs.items() if r.status != "completed"}
    m = {n: r.measurements for n, r in runs.items() if r.status == "completed"}
    v = {}
    notes = {}

    def first(bench, trace):
        values = m.get(bench, {}).get(trace)
        return values[0] if values else None

    for t in (25, 125):
        vd = first(f"rds_on_{t}C", "v(d)")
        v[f"rds_on_{t}C"] = vd / 16 if vd is not None else None
    if "vgs_th" in m:
        vg, ig = m["vgs_th"]["v(g)"], [-x for x in m["vgs_th"]["i(vg)"]]
        v["vgs_th"] = cross(vg, ig, 4e-3)
    vd = first("vsd", "v(d)")
    v["vsd"] = -vd if vd is not None else None
    w = 2 * math.pi * AC_FREQ
    if "caps_gate_ac" in m:
        v["ciss"] = -first("caps_gate_ac", "i(vg)").imag / w
        v["crss"] = first("caps_gate_ac", "i(vd)").imag / w
        notes["capacitance_sign_check"] = "CISS and CRSS use signed currents; a negative value indicates a sign-convention error"
    coss_curve = None
    if "coss_curve_ac" in raws:
        # With one AC frequency per step, LTspice indexes the points by the stepped
        # parameter ("vds") instead of by frequency.
        raw = raws["coss_curve_ac"]
        if raw.axis != "vds":
            raise SystemExit(f"unexpected COSS sweep axis {raw.axis!r}")
        volts = [x.real for x in raw.values["vds"]]
        coss = [-i.imag / w for i in raw.values["i(vd)"]]
        coss_curve = {"vds_V": volts, "coss_F": coss}
        v["coss"] = at(volts, coss, 50.0)
        upto = [k for k, x in enumerate(volts) if x <= BVDSS_HALF + 1e-9]
        vv, cc = [volts[k] for k in upto], [coss[k] for k in upto]
        q = cumtrapz(vv, cc)
        e = cumtrapz(vv, [c * x for c, x in zip(cc, vv)])
        notes["ac_integrated"] = {"qoss_C": q[-1], "eoss_J": e[-1], "points": len(volts),
                                  "method": "trapezoid of small-signal COSS over 0..50 V, 0.25 V spacing"}
    if "qoss_tran" in m:
        t, i, vdv = m["qoss_tran"]["time"], [-x for x in m["qoss_tran"]["i(vd)"]], m["qoss_tran"]["v(d)"]
        end = next(k for k, x in enumerate(t) if x >= 1e-6)
        q = cumtrapz(t[:end + 1], i[:end + 1])[-1]
        e = cumtrapz(t[:end + 1], [a * b for a, b in zip(i, vdv)][:end + 1])[-1]
        v["qoss"] = q
        v["coss_tr"] = q / BVDSS_HALF
        v["coss_er"] = 2 * e / BVDSS_HALF ** 2
        notes["transient"] = {"qoss_C": q, "eoss_J": e, "method": "integral of drain-source current over a 1 us 0 -> 50 V ramp"}
        if "ac_integrated" in notes:
            a = notes["ac_integrated"]
            notes["ac_vs_transient"] = {
                "qoss_relative_difference": abs(a["qoss_C"] - q) / q,
                "eoss_relative_difference": abs(a["eoss_J"] - e) / e,
                "tolerance": 0.02,
                "purpose": "checks that the model's small-signal and large-signal output charge agree in LTspice"}
            notes["ac_vs_transient"]["outcome"] = (
                "pass" if max(notes["ac_vs_transient"]["qoss_relative_difference"],
                              notes["ac_vs_transient"]["eoss_relative_difference"]) <= 0.02 else "fail")
    if "gate_charge_tran" in m:
        g = m["gate_charge_tran"]
        t, vg, vd, idc = g["time"], g["v(g)"], g["v(d)"], g["i(dc)"]
        q = cumtrapz(t, g["ix(x1:gatein)"])
        notes["gate_charge_initial_vgs_V"] = vg[0]
        tq = lambda x: None if x is None else at(t, q, x)
        t_g5 = cross(t, vg, 5.0)
        t_th = cross(t, vg, v["vgs_th"]) if v.get("vgs_th") else None
        t_gs = cross(t, idc, 0.16)  # clamp current below 1% of 16 A: FET carries the load
        t_gd = cross(t, vd, 5.0, start=t.index(next(x for x in t if t_gs and x >= t_gs)) if t_gs else 0)
        v["qg"], v["qg_th"], v["qgs"] = tq(t_g5), tq(t_th), tq(t_gs)
        v["qgd"] = tq(t_gd) - v["qgs"] if t_gd is not None and v["qgs"] is not None else None
        notes["gate_charge_definitions"] = {
            "qg": "charge delivered into the gate terminal (Ix(x1:gatein)) when VGS reaches 5 V",
            "qg_th": "gate charge when VGS reaches the model's VGS(th) from the vgs_th bench",
            "qgs": "gate charge when the clamp-diode current falls below 1% of 16 A (FET carries the load)",
            "qgd": "additional charge until VDS falls to 5 V (10% of 50 V)",
            "note": "QGS/QGD/QG(TH) boundary definitions are the bench's; EPC's exact extraction definitions are not stated"}
    table = {k: classify(k, v.get(k)) for k in DATASHEET}
    informational = {"rds_on_125C": v.get("rds_on_125C"),
                     "rds_on_ratio_125C_to_25C": (v["rds_on_125C"] / v["rds_on_25C"]
                                                  if v.get("rds_on_125C") and v.get("rds_on_25C") else None)}
    table["rds_on"] = classify("rds_on", v.get("rds_on_25C"))
    curves = {}
    if "output_curves_25C" in raws:
        raw = raws["output_curves_25C"]
        curves["output_25C"] = {f"vgs_{2 + k}V": {"vds_V": raw.step(k)["v(d)"],
                                                  "id_A": [-x for x in raw.step(k)["i(vd)"]]}
                                for k in range(raw.n_steps)}
    for t in (25, 125):
        name = f"transfer_curve_{t}C"
        if name in m:
            curves[f"transfer_vds3V_{t}C"] = {"vgs_V": m[name]["v(g)"], "id_A": [-x for x in m[name]["i(vd)"]]}
    if coss_curve:
        curves["coss_25C"] = coss_curve
    outcome = "completed" if not failed else "incomplete"
    report = {
        "schema": "epc2204-datasheet-baseline/1",
        "scope": ("Unmodified EPC2204 vendor model in LTspice compared with the datasheet table. "
                  "Datasheet values are vendor-described typical/limit values, not our measurements; "
                  "agreement here is model-to-datasheet consistency, not hardware validation."),
        "run_outcome": outcome,
        "failed_benches": failed,
        "evaluator_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        "model": {"library": LIB_NAME, "library_sha256": hashlib.sha256(lib.read_bytes()).hexdigest(),
                  "archive_sha256": archive_sha, "subcircuit": "EPC2204", "modified": False},
        "tool": asdict(ltspice_capability(args.executable)),
        "comparison_rules": {"limits": "inside/outside datasheet min-max",
                             "typical_only_screening_band": SCREENING_BAND,
                             "screening_meaning": "flags values for review; not an acceptance tolerance"},
        "datasheet_table": table,
        "informational": informational,
        "checks_and_definitions": notes,
        "evidence_directory": str(run_root.relative_to(ROOT)),
        "runs": {n: {"status": r.status, "message": r.message, "duration_s": r.duration_s,
                     "warnings": r.provenance.get("log_warnings"), "netlist_sha256": r.provenance.get("netlist_sha256")}
                 for n, r in runs.items()},
        "curves_file": str(args.curves.relative_to(ROOT)),
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2, allow_nan=False) + "\n")
    args.curves.write_text(json.dumps({"schema": "epc2204-model-curves/1", "model_library_sha256": report["model"]["library_sha256"],
                                       "temperature_note": "LTspice .temp sets the model's Temp parameter",
                                       "curves": curves}, allow_nan=False) + "\n")
    summary = {k: {"model": r["model"], "outcome": r["outcome"]} for k, r in table.items()}
    print(json.dumps({"run_outcome": outcome, "failed": failed, "table": summary,
                      "ac_vs_transient": notes.get("ac_vs_transient", {}).get("outcome"),
                      "report": str(args.output)}, indent=2, default=str))
    return 0 if outcome == "completed" else 2


if __name__ == "__main__":
    raise SystemExit(main())
