#!/usr/bin/env python3
"""Run the unmodified EPC2302 LTspice model at datasheet table conditions.

Stage 1 baseline for the selected EPC90133/EPC2302 target: vendor model ->
LTspice adapter -> parsed values compared with the EPC2302 datasheet table.
It follows scripts/epc2204_baseline.py, which stays unchanged as the accepted
EPC2204 evaluator. The EPC2302 subcircuit has the same structure as EPC2204
(only parameter values differ), so that script's charge-equation and leakage
helpers apply unchanged. Rules fixed before the first EPC2302 run:

* limit compliance and deviation from the typical value are reported
  separately; being inside a datasheet limit does not show model accuracy;
* a row is flagged for review when it is outside a datasheet limit or its
  deviation from the typical value exceeds SCREENING_BAND (a screening aid,
  not an acceptance tolerance);
* the drive-current check compares stored gate charge (QG minus the model's
  own gate leakage along each trajectory). EPC2204 showed that raw QG shifts
  with drive current through leakage; raw QG change is still reported.

The library archive is checked against devices/epc/sources.json and the
extracted library and datasheet against devices/epc/epc90133-sources.json.
"""
import argparse
from dataclasses import asdict
import hashlib
import json
import math
from pathlib import Path
import sys
import uuid

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))
from circuit_tools.ltspice import ltspice_capability, parse_raw, run_ltspice
from epc2204_baseline import (at, cross, cumtrapz, equation_gate_charge, leakage_charge,
                              library_path, subckt_params)

TARGET_SOURCES = ROOT / "devices" / "epc" / "epc90133-sources.json"
DATASHEET_PDF = "EPC2302_datasheet.pdf"
SUBCKT = "EPC2302"
SCREENING_BAND = 0.25
BVDSS_HALF = 50.0  # V; COSS(ER)/COSS(TR) are defined from 0 to 50% of BVDSS = 100 V

# EPC2302 datasheet, revised April 29, 2026, TJ = 25 C. Column (min/typ/max)
# assignment checked from word x-positions on page 2.
DATASHEET = {
    "rds_on":  {"unit": "ohm", "typ": 1.4e-3, "max": 1.8e-3, "conditions": "VGS = 5 V, ID = 50 A"},
    "vgs_th":  {"unit": "V", "min": 0.8, "typ": 1.3, "max": 2.5, "conditions": "VDS = VGS, ID = 14 mA"},
    "vsd":     {"unit": "V", "typ": 1.5, "conditions": "IS = 0.5 A, VGS = 0 V (defined by design)"},
    "ciss":    {"unit": "F", "typ": 3200e-12, "max": 4800e-12, "conditions": "VDS = 50 V, VGS = 0 V"},
    "crss":    {"unit": "F", "typ": 7e-12, "conditions": "VDS = 50 V, VGS = 0 V"},
    "coss":    {"unit": "F", "typ": 1000e-12, "max": 1200e-12, "conditions": "VDS = 50 V, VGS = 0 V"},
    "coss_er": {"unit": "F", "typ": 1300e-12, "conditions": "VDS = 0 to 50 V, VGS = 0 V"},
    "coss_tr": {"unit": "F", "typ": 1700e-12, "conditions": "VDS = 0 to 50 V, VGS = 0 V"},
    "qg":      {"unit": "C", "typ": 23e-9, "max": 29e-9, "conditions": "VDS = 50 V, VGS = 5 V, ID = 50 A"},
    "qgs":     {"unit": "C", "typ": 8.9e-9, "conditions": "VDS = 50 V, ID = 50 A"},
    "qgd":     {"unit": "C", "typ": 2.3e-9, "conditions": "VDS = 50 V, ID = 50 A"},
    "qg_th":   {"unit": "C", "typ": 6.3e-9, "conditions": "VDS = 50 V, ID = 50 A"},
    "qoss":    {"unit": "C", "typ": 85e-9, "max": 94e-9, "conditions": "VDS = 50 V, VGS = 0 V"},
}
VTH_CURRENT = 14e-3  # A
RDS_CURRENT = 50.0  # A
LOAD_CURRENT = 50.0  # A, gate-charge bench

AC_FREQ = 1e6  # Hz; Rg = 0.5 ohm, CISS ~3.2 nF: series-resistance error ~(w Rg C)^2 ~ 1e-4
GATE_CURRENT = 40e-3  # A; QG ~23 nC reaches 5 V in ~0.6 us, as the EPC2204 bench did at 10 mA
LOW_GATE_CURRENT = 8e-3  # A; same 5:1 ratio as the EPC2204 sensitivity check
R_HOLD = 100e3  # ohm, gate hold-down resistor in the gate-charge bench
HEAD = f"* {SUBCKT} unmodified vendor model; bench generated by scripts/epc2302_baseline.py\n.lib EPCGaNLibrary.lib\n"
# LTspice's default reltol under-integrated EPC2204's on-state gate charge (docs/build.md);
# use 1e-6 and confirm with 1e-7 and with the default, as for EPC2204.
RELTOL = 1e-6
RELTOL_OVERRIDES = {"gate_charge_tran_reltol1e-7": 1e-7, "gate_charge_tran_default_reltol": None}
CONVERGENCE_TOLERANCE = 0.005  # relative QG change for reltol 1e-6 -> 1e-7, and stored-charge change for drive current
EQUATION_TOLERANCE = 0.01  # relative agreement between transient QG and the model's charge equations


def benches():
    b = {}
    for t in (25, 125):
        # A 0 -> 50 A sweep instead of .op: the direct 125 C operating point failed
        # Gmin and source stepping on the first run; the sweep gives continuation.
        b[f"rds_on_{t}C"] = HEAD + f"""* RDS(on): VGS = 5 V, drain current swept to {RDS_CURRENT:g} A
Vg g 0 5
Id 0 d 0
X1 g d 0 {SUBCKT}
.temp {t}
.dc Id 0 {RDS_CURRENT:g} 0.5
.end
"""
    b["vgs_th"] = HEAD + f"""* VGS(th): drain tied to gate, sweep until ID = {VTH_CURRENT * 1e3:g} mA
Vg g 0 0
X1 g g 0 {SUBCKT}
.temp 25
.dc Vg 0 3 1m
.end
"""
    b["vsd"] = HEAD + f"""* VSD: 0.5 A reverse conduction, VGS = 0 V
Vg g 0 0
Is d 0 0.5
X1 g d 0 {SUBCKT}
.temp 25
.op
.end
"""
    b["caps_gate_ac"] = HEAD + f"""* CISS and CRSS: AC on gate, drain held at 50 V (AC ground)
Vg g 0 0 AC 1
Vd d 0 50
X1 g d 0 {SUBCKT}
.temp 25
.ac list {AC_FREQ:g}
.end
"""
    b["coss_curve_ac"] = HEAD + f"""* COSS(VDS): AC on drain, gate and source AC-grounded, VDS stepped 0..100 V
.param vds=50
Vd d 0 {{vds}} AC 1
Vg g 0 0
X1 g d 0 {SUBCKT}
.temp 25
.step param vds 0 100 0.25
.ac list {AC_FREQ:g}
.end
"""
    b["qoss_tran"] = HEAD + f"""* QOSS/EOSS: drain ramped 0 -> 50 V in 1 us, VGS = 0 V
Vd d 0 PWL(0 0 1u 50 1.5u 50)
Vg g 0 0
X1 g d 0 {SUBCKT}
.temp 25
.options plotwinsize=0
.tran 0 1.5u 0 1n
.end
"""
    for label, current, stop in (("", GATE_CURRENT, "1.5u"), ("_low_drive", LOW_GATE_CURRENT, "5u"),
                                 ("_reltol1e-7", GATE_CURRENT, "1.5u"),
                                 ("_default_reltol", GATE_CURRENT, "1.5u")):
        b["gate_charge_tran" + label] = HEAD + f"""* Gate charge: 50 V supply, {LOAD_CURRENT:g} A load current with ideal clamp diode, {current*1e3:g} mA gate current
Vdd vdd 0 50
Il vdd d {LOAD_CURRENT:g}
Dc d vdd dclamp
.model dclamp D(Ron=1m Roff=1G Vfwd=0)
Ig 0 g PULSE(0 {current:g} 100n 1n 1n 5u 10u)
* Hold-down resistor keeps the floating gate below VGS(th) before the pulse.
* Charge is integrated from the gate terminal current.
Rhold g 0 {R_HOLD:g}
X1 g d 0 {SUBCKT}
.temp 25
.options plotwinsize=0
.tran 0 {stop} 0 0.1n
.end
"""
    b["output_curves_25C"] = HEAD + f"""* Output characteristics (datasheet Fig. 1 axes): VDS 0..3 V, VGS 2..5 V
Vd d 0 0
Vg g 0 0
X1 g d 0 {SUBCKT}
.temp 25
.dc Vd 0 3 10m Vg 2 5 1
.end
"""
    for t in (25, 125):
        b[f"transfer_curve_{t}C"] = HEAD + f"""* Transfer characteristic (datasheet Fig. 2 axes): VDS = 3 V
Vd d 0 3
Vg g 0 0
X1 g d 0 {SUBCKT}
.temp {t}
.dc Vg 0 5 10m
.end
"""
    return b


def classify(name, value):
    row = dict(DATASHEET[name])
    row["model"] = value
    if value is None:
        row.update(limit_check="not-measured", typical_check="not-measured", review=True)
        return row
    if "min" in row or "max" in row:
        inside = row.get("min", -math.inf) <= value <= row.get("max", math.inf)
        row["limit_check"] = "inside-limits" if inside else "outside-limits"
    else:
        row["limit_check"] = "no-limits"
    row["deviation_from_typ"] = value / row["typ"] - 1
    row["typical_check"] = ("within-screening-band" if abs(row["deviation_from_typ"]) <= SCREENING_BAND
                            else "outside-screening-band")
    row["review"] = row["limit_check"] == "outside-limits" or row["typical_check"] == "outside-screening-band"
    return row


def gate_charge(g, vgs_th):
    """Gate-charge quantities, bench self-checks and trajectory states from one transient."""
    t, vg, vd, idc = g["time"], g["v(g)"], g["v(d)"], g["i(dc)"]
    ig, ipin, idrain = g["i(ig)"], g["ix(x1:gatein)"], g["ix(x1:drainin)"]
    q = cumtrapz(t, ipin)
    tq = lambda x: None if x is None else at(t, q, x)

    def after(x):
        return next(k for k, tt in enumerate(t) if tt >= x) if x is not None else 0

    t_g5 = cross(t, vg, 5.0)
    t_th = cross(t, vg, vgs_th) if vgs_th else None
    t_gs = {f: cross(t, idc, f * LOAD_CURRENT) for f in (0.1, 0.01, 0.001)}
    t_gd = {x: cross(t, vd, x, start=after(t_gs[0.01])) for x in (10.0, 5.0, 1.0)}
    values = {"qg": tq(t_g5), "qg_th": tq(t_th), "qgs": tq(t_gs[0.01])}
    values["qgd"] = (tq(t_gd[5.0]) - values["qgs"]) if t_gd[5.0] is not None and values["qgs"] is not None else None
    if t_g5 is None:
        return values, {"error": "VGS never reached 5 V"}, None, None
    k5 = after(t_g5)
    q_half = cumtrapz(t[::2], ipin[::2])
    qg_half = at(t[::2], q_half, t_g5)
    residual = [a - b - c / R_HOLD for a, b, c in zip(ig, ipin, vg)]
    checks = {
        "starting_bias": {"vgs_V": vg[0], "vds_V": vd[0], "clamp_current_A": idc[0], "fet_drain_current_A": idrain[0],
                          "expect": f"VGS near 0, VDS near 50 V, {LOAD_CURRENT:g} A in the clamp, FET off"},
        "gate_current_balance": {
            "definition": "I(Ig) - Ix(X1:gatein) - V(g)/Rhold at every time point",
            "max_abs_residual_A": max(abs(r) for r in residual),
            "hold_resistor_current_at_5V_A": vg[k5] / R_HOLD},
        "integration_resolution": {
            "qg_full_C": values["qg"], "qg_every_other_sample_C": qg_half,
            "relative_difference": abs(qg_half - values["qg"]) / values["qg"]},
        "drain_transition_at_vgs_5V": {"vds_V": vd[k5], "fet_drain_current_A": idrain[k5], "clamp_current_A": idc[k5],
                                       "expect": f"VDS near {LOAD_CURRENT:g} A x RDS(on), FET carries the load"},
        "miller_plateau_vgs_V": at(t, vg, t_gs[0.01]) if t_gs[0.01] else None,
        "endpoint_sensitivity": {
            "qgs_C_by_clamp_threshold_fraction": {str(f): tq(x) for f, x in t_gs.items()},
            "qgd_C_by_vds_end_V": {str(x): (tq(tt) - values["qgs"]) if tt is not None and values["qgs"] else None
                                   for x, tt in t_gd.items()}},
    }
    states = {"t_g5": t_g5, "start": (vg[0], vd[0], idrain[0], ipin[0]),
              "vgs_5V": (vg[k5], vd[k5], idrain[k5], ipin[k5])}
    step = max(1, len(t) // 400)
    curve = {"qg_C": q[:k5 + 1:step], "vgs_V": vg[:k5 + 1:step], "vds_V": vd[:k5 + 1:step]}
    return values, checks, curve, states


def verify_target_sources(lib):
    """Check the extracted library and the datasheet against the EPC90133 source record."""
    rec = json.loads(TARGET_SOURCES.read_text(encoding="utf-8"))
    lib_sha = hashlib.sha256(lib.read_bytes()).hexdigest()
    if lib_sha != rec["model"]["sha256"]:
        raise SystemExit(f"{lib} sha256 {lib_sha} does not match {TARGET_SOURCES.name} ({rec['model']['sha256']})")
    entry = next(f for f in rec["files"] if f["name"] == DATASHEET_PDF)
    pdf = ROOT / entry["local_path"]
    pdf_sha = hashlib.sha256(pdf.read_bytes()).hexdigest() if pdf.is_file() else None
    if pdf_sha != entry["sha256"]:
        raise SystemExit(f"{pdf} sha256 {pdf_sha} does not match the recorded {entry['sha256']}; "
                         "the DATASHEET table was transcribed from that revision")
    return lib_sha, {"file": entry["local_path"], "revision": entry["revision"], "sha256": pdf_sha}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--executable", default=None)
    parser.add_argument("--output", type=Path, default=ROOT / "results/gan/epc2302-baseline.json")
    parser.add_argument("--curves", type=Path, default=ROOT / "results/gan/epc2302-model-curves.json")
    args = parser.parse_args()
    lib, archive_sha = library_path()
    lib_sha, datasheet = verify_target_sources(lib)
    run_root = ROOT / "runs" / ("epc2302-baseline-" + uuid.uuid4().hex)
    runs, raws = {}, {}
    for name, text in benches().items():
        reltol = RELTOL_OVERRIDES.get(name, RELTOL)
        if reltol is not None:
            text = text.replace("\n.end\n", f"\n.options reltol={reltol:g}\n.end\n")
        r = run_ltspice(text, run_root / name, libraries=[lib], executable=args.executable, timeout_s=600)
        runs[name] = r
        if r.status == "completed" and r.result_path:
            raws[name] = parse_raw(r.result_path)
    failed = {n: r.message for n, r in runs.items() if r.status != "completed"}
    m = {n: r.measurements for n, r in runs.items() if r.status == "completed"}
    v, notes = {}, {}

    def first(bench, trace):
        values = m.get(bench, {}).get(trace)
        return values[0] if values else None

    for t in (25, 125):
        bench = m.get(f"rds_on_{t}C")
        v[f"rds_on_{t}C"] = at(bench["i(id)"], bench["v(d)"], RDS_CURRENT) / RDS_CURRENT if bench else None
    if "vgs_th" in m:
        vg, ig = m["vgs_th"]["v(g)"], [-x for x in m["vgs_th"]["i(vg)"]]
        v["vgs_th"] = cross(vg, ig, VTH_CURRENT)
    vd = first("vsd", "v(d)")
    v["vsd"] = -vd if vd is not None else None
    w = 2 * math.pi * AC_FREQ
    if "caps_gate_ac" in m:
        v["ciss"] = -first("caps_gate_ac", "i(vg)").imag / w
        v["crss"] = first("caps_gate_ac", "i(vd)").imag / w
        notes["capacitance_sign_check"] = "CISS and CRSS use signed currents; a negative value indicates a sign-convention error"
    coss_curve = None
    if "coss_curve_ac" in raws:
        raw = raws["coss_curve_ac"]
        if raw.axis != "vds":
            raise SystemExit(f"unexpected COSS sweep axis {raw.axis!r}")
        volts = [x.real for x in raw.values["vds"]]
        coss = [-i.imag / w for i in raw.values["i(vd)"]]
        coss_curve = {"vds_V": volts, "coss_F": coss}
        v["coss"] = at(volts, coss, 50.0)
        upto = [k for k, x in enumerate(volts) if x <= BVDSS_HALF + 1e-9]
        vv, cc = [volts[k] for k in upto], [coss[k] for k in upto]
        notes["ac_integrated"] = {"qoss_C": cumtrapz(vv, cc)[-1],
                                  "eoss_J": cumtrapz(vv, [c * x for c, x in zip(cc, vv)])[-1],
                                  "method": "trapezoid of small-signal COSS over 0..50 V, 0.25 V spacing"}
    if "qoss_tran" in m:
        t, i, vdv = m["qoss_tran"]["time"], [-x for x in m["qoss_tran"]["i(vd)"]], m["qoss_tran"]["v(d)"]
        end = next(k for k, x in enumerate(t) if x >= 1e-6)
        q = cumtrapz(t[:end + 1], i[:end + 1])[-1]
        e = cumtrapz(t[:end + 1], [a * b for a, b in zip(i, vdv)][:end + 1])[-1]
        v["qoss"], v["coss_tr"], v["coss_er"] = q, q / BVDSS_HALF, 2 * e / BVDSS_HALF ** 2
        notes["transient"] = {"qoss_C": q, "eoss_J": e, "method": "integral of drain-source current over a 1 us 0 -> 50 V ramp"}
        if "ac_integrated" in notes:
            a = notes["ac_integrated"]
            dq, de = abs(a["qoss_C"] - q) / q, abs(a["eoss_J"] - e) / e
            notes["ac_vs_transient"] = {
                "qoss_relative_difference": dq, "eoss_relative_difference": de, "tolerance": 0.02,
                "outcome": "pass" if max(dq, de) <= 0.02 else "fail",
                "purpose": "checks that the model's small-signal and large-signal output charge agree in LTspice"}
    gate_curve = None
    if "gate_charge_tran" in m:
        values, checks, gate_curve, states = gate_charge(m["gate_charge_tran"], v.get("vgs_th"))
        v.update(values)
        notes["gate_charge_checks"] = checks
        if states:
            P = subckt_params(lib.read_text(encoding="utf-8", errors="replace"), SUBCKT)
            q_eq = equation_gate_charge(P, states["start"], states["vgs_5V"])
            diff = abs(values["qg"] - q_eq) / q_eq
            notes["gate_charge_equation_check"] = {
                "qg_from_model_equations_C": q_eq, "qg_transient_C": values["qg"],
                "relative_difference": diff, "tolerance": EQUATION_TOLERANCE,
                "outcome": "pass" if diff <= EQUATION_TOLERANCE else "fail",
                "method": (f"Q_gate(end) - Q_gate(start) from the {SUBCKT} charge equations (same form as EPC2204), "
                           "parameters read from the local library, at the simulated start and VGS = 5 V states")}
            conv = {}
            if "gate_charge_tran_reltol1e-7" in m:
                tight = gate_charge(m["gate_charge_tran_reltol1e-7"], v.get("vgs_th"))[0]
                conv["qg_reltol_1e-7_C"] = tight["qg"]
                conv["relative_change_1e-6_to_1e-7"] = abs(tight["qg"] / values["qg"] - 1) if tight["qg"] else None
            if "gate_charge_tran_default_reltol" in m:
                conv["qg_default_reltol_C"] = gate_charge(m["gate_charge_tran_default_reltol"], v.get("vgs_th"))[0]["qg"]
                conv["default_reltol_note"] = "LTspice default reltol (1e-3); recorded to show whether the EPC2204 artifact recurs"
            conv["tolerance"] = CONVERGENCE_TOLERANCE
            change = conv.get("relative_change_1e-6_to_1e-7")
            conv["outcome"] = "pass" if change is not None and change <= CONVERGENCE_TOLERANCE else "fail"
            notes["gate_charge_numerical_convergence"] = conv
            if "gate_charge_tran_low_drive" in m:
                low, low_checks, _, low_states = gate_charge(m["gate_charge_tran_low_drive"], v.get("vgs_th"))
                if low_states:
                    leak_nom = leakage_charge(P, m["gate_charge_tran"], states["t_g5"])
                    leak_low = leakage_charge(P, m["gate_charge_tran_low_drive"], low_states["t_g5"])
                    stored_nom, stored_low = values["qg"] - leak_nom, low["qg"] - leak_low
                    stored_diff = abs(stored_low / stored_nom - 1)
                    notes["gate_charge_drive_current_sensitivity"] = {
                        "drive_currents_A": [GATE_CURRENT, LOW_GATE_CURRENT],
                        "values_at_low_drive_C": low,
                        "raw_relative_change": {k: (low[k] / values[k] - 1) if low.get(k) and values.get(k) else None
                                                for k in values},
                        "leakage_charge_to_vgs_5V_C": {"nominal": leak_nom, "low_drive": leak_low},
                        "stored_charge_qg_minus_leakage_C": {"nominal": stored_nom, "low_drive": stored_low},
                        "stored_charge_relative_difference": stored_diff,
                        "gate_current_balance_low_drive": low_checks["gate_current_balance"],
                        "tolerance": CONVERGENCE_TOLERANCE,
                        "outcome": "pass" if stored_diff <= CONVERGENCE_TOLERANCE else "fail",
                        "criterion": "declared before the first EPC2302 run: stored charge, i.e. QG minus the model's "
                                     "gate-diode and convergence-resistor charge along each trajectory",
                        "purpose": "a charge-based model stores the same charge at any drive current"}
        notes["gate_charge_definitions"] = {
            "qg": f"charge delivered into the gate terminal (Ix(x1:gatein)) when VGS reaches 5 V; {GATE_CURRENT*1e3:g} mA drive",
            "qg_th": "gate charge when VGS reaches the model's VGS(th) from the vgs_th bench",
            "qgs": f"gate charge when the clamp-diode current falls below 1% of {LOAD_CURRENT:g} A (FET carries the load)",
            "qgd": "additional charge until VDS falls to 5 V (10% of 50 V)",
            "note": ("QGS/QGD/QG(TH) boundary definitions are the bench's; EPC's exact extraction definitions are "
                     "not stated. For EPC2204 these sub-charges stayed unresolved even against EPC's own curve.")}
    table = {k: classify(k, v.get(k)) for k in DATASHEET}
    table["rds_on"] = classify("rds_on", v.get("rds_on_25C"))
    informational = {"rds_on_125C": v.get("rds_on_125C"),
                     "rds_on_ratio_125C_to_25C": (v["rds_on_125C"] / v["rds_on_25C"]
                                                  if v.get("rds_on_125C") and v.get("rds_on_25C") else None),
                     "datasheet_rg_ohm": 0.5,
                     "model_rg_value_ohm": subckt_params(lib.read_text(encoding="utf-8", errors="replace"), SUBCKT)["rg_value"]}
    curves = {}
    if "output_curves_25C" in raws:
        raw = raws["output_curves_25C"]
        curves["output_25C"] = {f"vgs_{2 + k}V": {"vds_V": raw.step(k)["v(d)"],
                                                  "id_A": [-x for x in raw.step(k)["i(vd)"]]}
                                for k in range(raw.n_steps)}
    for t in (25, 125):
        name = f"transfer_curve_{t}C"
        if name in m:
            curves[f"transfer_vds3V_{t}C"] = {"vgs_V": m[name]["v(g)"], "id_A": [-x for x in m[name]["i(vd)"]]}
    if coss_curve:
        curves["coss_25C"] = coss_curve
    if gate_curve:
        curves[f"gate_charge_25C_vds50V_{LOAD_CURRENT:g}A"] = gate_curve
    outcome = "completed" if not failed else "incomplete"
    report = {
        "schema": "epc2302-datasheet-baseline/1",
        "scope": ("Unmodified EPC2302 vendor model in LTspice compared with the EPC2302 datasheet table. "
                  "Datasheet values are vendor-described typical/limit values, not our measurements; "
                  "agreement here is model-to-datasheet consistency, not hardware validation. "
                  "No EPC2204/EPC9097 result is reused as evidence."),
        "run_outcome": outcome,
        "failed_benches": failed,
        "evaluator_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        "helper_module_sha256": hashlib.sha256((ROOT / "scripts/epc2204_baseline.py").read_bytes()).hexdigest(),
        "model": {"library": "EPCGaNLibrary.lib", "library_sha256": lib_sha,
                  "archive_sha256": archive_sha, "subcircuit": SUBCKT, "modified": False},
        "datasheet": datasheet,
        "tool": asdict(ltspice_capability(args.executable)),
        "comparison_rules": {"limit_check": "inside/outside datasheet min-max; does not establish accuracy",
                             "typical_check_screening_band": SCREENING_BAND,
                             "review": "outside a limit, or deviation from typical beyond the band",
                             "screening_meaning": "flags values for review; not an acceptance tolerance"},
        "datasheet_table": table,
        "informational": informational,
        "checks_and_definitions": notes,
        "evidence_directory": str(run_root.relative_to(ROOT)),
        "runs": {n: {"status": r.status, "message": r.message, "duration_s": r.duration_s,
                     "warnings": r.provenance.get("log_warnings"), "netlist_sha256": r.provenance.get("netlist_sha256")}
                 for n, r in runs.items()},
        "curves_file": str(args.curves.relative_to(ROOT)),
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2, allow_nan=False) + "\n")
    args.curves.write_text(json.dumps({"schema": "epc2302-model-curves/1", "model_library_sha256": lib_sha,
                                       "temperature_note": "LTspice .temp sets the model's Temp parameter",
                                       "curves": curves}, allow_nan=False) + "\n")
    summary = {k: {"model": r["model"], "limit": r["limit_check"],
                   "dev_from_typ": r.get("deviation_from_typ"), "review": r["review"]} for k, r in table.items()}
    print(json.dumps({"run_outcome": outcome, "failed": failed, "table": summary,
                      "informational": informational,
                      "ac_vs_transient": notes.get("ac_vs_transient", {}).get("outcome"),
                      "gate_charge_equation_check": notes.get("gate_charge_equation_check", {}).get("outcome"),
                      "gate_charge_convergence": notes.get("gate_charge_numerical_convergence", {}).get("outcome"),
                      "gate_charge_drive_current": notes.get("gate_charge_drive_current_sensitivity", {}).get("outcome"),
                      "report": str(args.output)}, indent=2, default=str))
    return 0 if outcome == "completed" else 2


if __name__ == "__main__":
    raise SystemExit(main())
