#!/usr/bin/env python3
"""Check the BOM-based EPC90133 schematic and run its LTspice netlist through static states.

devices/epc/epc90133-schematic.json holds the power stage transcribed from the
QSG schematic (Figs. 13-15), with values set by the BOM. This script:

1. checks every component's BOM part number against the recorded BOM file;
2. emits the LTspice netlist of the power stage: two unmodified EPC2302 models,
   the gate resistors, the individual loop and intermediate capacitors, and the
   behavioural uP1966E output stages of scripts/epc9097_switching.py (calibrated
   to the uP1966E datasheet, not to any EPC9097 measurement), with an ideal 5 V
   high-side supply across C81;
3. runs a static-state check: 48 V bus and a 48 ohm load from SW to a 24 V midpoint.
   Low side on: SW < 1 V. Both off (after 2 us): SW within 1 V of 24 V. High side on:
   SW > 47 V. Each gate within 0.1 V of 5 V relative to its source while on.

This establishes that the netlist is connected as the schematic says. It makes
no switching-time or loss claim: layout parasitics are absent, and EPC2302's
Fig. 7 gate-charge mismatch is unresolved (G2 exception).
"""
import argparse
import hashlib
import json
from pathlib import Path
import sys
import uuid

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))
from audit_epc90133_board_files import read_bom, verified
from circuit_tools.ltspice import run_ltspice
import epc2302_baseline as bl
from epc9097_switching import SWITCH_MODELS, drive_stage

SCHEMATIC = ROOT / "devices/epc/epc90133-schematic.json"
VIN, VMID, R_LOAD, VCC = 48.0, 24.0, 48.0, 5.0
R_SRC, R_SNK = 0.7, 0.4  # ohm, uP1966E typical output resistance (datasheet)
EDGE = 5e-9  # s, driver source ramp for this static check only
# Run 1 sampled "both off" 30 ns after turn-off and failed (SW 2.4 V): charging both FETs'
# output capacitance through 48 ohm takes hundreds of ns. Its report is kept as
# results/gan/epc90133-schematic-check-run1-failed.json. Revised check, declared before run 2:
# a 2 us both-off interval, sampled at its end.
T_END = 2.4e-6
LOW_ON, HIGH_ON = (20e-9, 120e-9), (2.12e-6, 2.22e-6)
SAMPLES = {"low_side_on": 110e-9, "both_off": 2.1e-6, "high_side_on": 2.21e-6}


def expand(ref):
    if "-" in ref:
        a, b = ref.split("-")
        stem = a.rstrip("0123456789")
        return [f"{stem}{k}" for k in range(int(a[len(stem):]), int(b[len(stem):]) + 1)]
    return [r.strip() for r in ref.split(",")]


def bom_check(sch, fitted):
    rows = []
    for c in sch["components"]:
        for ref in expand(c["ref"]):
            got = fitted.get(ref, {}).get("part_number")
            rows.append({"ref": ref, "schematic_json": c["bom_part"], "bom": got, "match": got == c["bom_part"]})
    return rows


def netlist(sch):
    comp = {c["ref"]: c for c in sch["components"]}
    r = lambda ref: max(comp[ref]["value"], 1e-6)  # 0-ohm jumpers as 1 micro-ohm
    lines = [f"* EPC90133 power stage from {SCHEMATIC.name}; generated by scripts/epc90133_schematic.py", ".lib EPCGaNLibrary.lib",
             f"XQ1 VGu VIN SW {comp['Q1']['model']}", f"XQ2 VGl SW 0 {comp['Q2']['model']}"]
    for group in ("Ci1-Ci7", "Cm1-Cm10"):
        for ref in expand(group):
            lines.append(f"C{ref} VIN 0 {comp[group]['value']:g}")
    lines += [f"Vin VIN 0 {VIN:g}", f"Vmid MID 0 {VMID:g}", f"Rload SW MID {R_LOAD:g}",
              f"CC81 5VHS1 SW {comp['C81']['value']:g}", f"Vhs 5VHS1 SW {VCC:g}",
              f"CC80 VDRV 0 {comp['C80']['value']:g}", f"Vdrv VDRV 0 {VCC:g}"]
    lines.append(drive_stage("u", "SW", VCC, [(HIGH_ON[0], 1), (HIGH_ON[1], 0)], EDGE, EDGE, "VGu",
                             R_SRC, R_SNK, r("R80"), r("R81"), T_END).rstrip())
    lines.append(drive_stage("l", "0", VCC, [(LOW_ON[0], 1), (LOW_ON[1], 0)], EDGE, EDGE, "VGl",
                             R_SRC, R_SNK, r("R82"), r("R83"), T_END).rstrip())
    lines += [SWITCH_MODELS.rstrip(), f".options plotwinsize=0 reltol={bl.RELTOL:g}", f".tran 0 {T_END:g} 0 0.1n", ".end", ""]
    return "\n".join(lines)


def value_at(t, y, x):
    return bl.at(t, y, x)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", type=Path, default=ROOT / "results/gan/epc90133-schematic-check.json")
    args = ap.parse_args()
    sch = json.loads(SCHEMATIC.read_text(encoding="utf-8"))
    fitted, _ = read_bom(verified("EPC90133BOM.xlsx"))
    rows = bom_check(sch, fitted)
    lib, _ = bl.library_path()
    bl.verify_target_sources(lib)
    text = netlist(sch)
    run_root = ROOT / "runs" / ("epc90133-schematic-" + uuid.uuid4().hex)
    res = run_ltspice(text, run_root / "static_states", libraries=[lib], timeout_s=600)
    states = {}
    if res.status == "completed":
        m = res.measurements
        t = m["time"]
        for name, ts in SAMPLES.items():
            states[name] = {"t_s": ts, "v_sw": value_at(t, m["v(sw)"], ts),
                            "vgs_high": value_at(t, m["v(vgu)"], ts) - value_at(t, m["v(sw)"], ts),
                            "vgs_low": value_at(t, m["v(vgl)"], ts)}
    s = states
    checks = {} if not s else {
        "low_side_on_sw_below_1V": s["low_side_on"]["v_sw"] < 1.0,
        "both_off_sw_at_midpoint": abs(s["both_off"]["v_sw"] - VMID) < 1.0,
        "high_side_on_sw_above_47V": s["high_side_on"]["v_sw"] > 47.0,
        "low_gate_at_5V_when_on": abs(s["low_side_on"]["vgs_low"] - VCC) < 0.1,
        "high_gate_at_5V_when_on": abs(s["high_side_on"]["vgs_high"] - VCC) < 0.1,
    }
    report = {
        "schema": "epc90133-schematic-check/1",
        "scope": "Netlist connectivity and static states only; no switching-time or loss claim.",
        "evaluator_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        "schematic_sha256": hashlib.sha256(SCHEMATIC.read_bytes()).hexdigest(),
        "bom_check": {"all_match": all(r["match"] for r in rows), "rows": rows},
        "label_discrepancies": sch["label_discrepancies"],
        "run": {"status": res.status, "message": res.message, "evidence": str((run_root / "static_states").relative_to(ROOT))},
        "states": states, "checks": checks,
        "outcome": "pass" if checks and all(checks.values()) and all(r["match"] for r in rows) else "fail",
    }
    args.output.write_text(json.dumps(report, indent=1) + "\n")
    print(json.dumps({k: report[k] for k in ("outcome", "states", "checks")}, indent=1))
    print("BOM mismatches:", [r for r in rows if not r["match"]])


if __name__ == "__main__":
    main()
