#!/usr/bin/env python3
"""Known-answer qualification of FastHenry before any board extraction (G3).

FastHenry 3.0.1 (MIT; ediloren/FastHenry2 master) is built locally under WSL
in the git-ignored .tools/FastHenry2 (see docs/build.md). Its licence allows
internal, noncommercial use only and forbids redistribution, so neither the
source nor the binary is committed.

Cases and tolerances, fixed before the first run:

A. Isolated copper bar, 10 x 1 x 0.035 mm, 1 Hz (uniform current): partial
   self-inductance against Grover's rectangular-bar formula. Tolerance 1 %.
B. Go-and-return pair of the same bars, 5 mm apart, shorted ideally at the
   far end, 1 Hz: loop inductance 2 (L - M) with Grover's mutual inductance
   of parallel filaments at the centre distance. Tolerance 1 %.
C. Parallel-plate loop at the EPC9097 6-layer spacing: two 10 mm wide,
   35 um thick copper strips with a 0.127 mm inner gap, shorted at the far
   end, 100 MHz. Inductance per unit length from the difference between a
   20 mm and a 10 mm loop (removes end and port effects), against
   mu0 h / w with Palmer's fringing correction. Tolerance 3 % (Palmer's
   correction is itself approximate and the strips have finite thickness).
Every case is run on three meshes; the two finest must agree within 1 %.

Result of the first run (28 September 2026): A and B pass; C fails (+4.9 %,
mesh converged to 0.13 %). Diagnosis after the failure: Palmer's formula is for
perfect conductors, while copper at 100 MHz carries current in a 6.6 um skin
depth, adding about mu0 delta / w of internal inductance (delta / h = 5.2 %).
C's declared reference therefore omitted physics; its failure is kept in the
report. A new check was declared before it was run:

D. The same plates at 1 GHz. (i) Inductance per unit length against Palmer's
   formula with the gap increased by one skin depth (half a skin depth per
   conductor), tolerance 3 %. (ii) The ratio of the 1 GHz and 100 MHz values
   against (h + delta_1GHz) / (h + delta_100MHz), tolerance 1 %; this
   frequency dependence is a prediction with nothing fitted.
"""
import argparse
import hashlib
import json
import math
import os
from pathlib import Path
import platform
import re
import subprocess
import uuid

ROOT = Path(__file__).resolve().parents[1]
FH_DIR = ROOT / ".tools" / "FastHenry2"
FH_BIN = FH_DIR / "bin" / "fasthenry"
MU0 = 4e-7 * math.pi
SIGMA_CU_PER_MM = 5.8e4  # 1/(ohm mm): 5.8e7 S/m in FastHenry's mm units
MESH_TOLERANCE = 0.01
TOL = {"A": 0.01, "B": 0.01, "C": 0.03, "D_absolute": 0.03, "D_ratio": 0.01}
RHO_CU = 1 / 5.8e7  # ohm m


def wsl_path(p):
    p = Path(p).resolve()
    return "/mnt/" + p.drive[0].lower() + p.as_posix()[2:]


def run_fasthenry(inp_text, workdir):
    """Write the input, run FastHenry in workdir, and return {frequency: impedance} for a 1x1 port."""
    workdir.mkdir(parents=True, exist_ok=False)
    (workdir / "case.inp").write_text(inp_text, encoding="ascii")
    if platform.system() == "Windows":
        cmd = ["wsl", "-e", "bash", "-lc", f"cd '{wsl_path(workdir)}' && '{wsl_path(FH_BIN)}' case.inp"]
    else:
        cmd = [str(FH_BIN), "case.inp"]
    p = subprocess.run(cmd, cwd=workdir, capture_output=True, text=True, timeout=1800, check=False)
    (workdir / "stdout.log").write_text(p.stdout or "", encoding="utf-8")
    (workdir / "stderr.log").write_text(p.stderr or "", encoding="utf-8")
    zc = workdir / "Zc.mat"
    if p.returncode != 0 or not zc.is_file():
        raise RuntimeError(f"FastHenry failed in {workdir} (status {p.returncode}): {(p.stderr or p.stdout)[-500:]}")
    return parse_zc(zc.read_text(encoding="ascii", errors="replace")), p.stdout


def parse_zc(text):
    """Parse FastHenry's Zc.mat for one-port runs: {frequency_Hz: complex impedance}."""
    out = {}
    lines = text.splitlines()
    for i, line in enumerate(lines):
        m = re.match(r"\s*Impedance matrix for frequency\s*=\s*(\S+)\s+(\d+)\s*x\s*(\d+)", line)
        if not m:
            continue
        if (m.group(2), m.group(3)) != ("1", "1"):
            raise ValueError("only 1x1 impedance matrices are expected")
        num = r"[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?"
        z = re.match(rf"\s*({num})\s*([-+])\s*({num})j", lines[i + 1])
        if not z:
            raise ValueError(f"cannot parse impedance line: {lines[i + 1]!r}")
        imag = float(z.group(3)) * (1 if z.group(2) == "+" else -1)
        out[float(m.group(1))] = complex(float(z.group(1)), imag)
    if not out:
        raise ValueError("no impedance matrix in Zc.mat")
    return out


def head(title, freq):
    return (f"* {title}; generated by scripts/fasthenry_known_answer.py\n.units mm\n"
            f".default sigma={SIGMA_CU_PER_MM:g}\n"), f".freq fmin={freq:g} fmax={freq:g} ndec=1\n.end\n"


def case_a(mesh):
    top, tail = head("A: isolated bar", 1.0)
    return top + f"""N1 x=0 y=0 z=0
N2 x=10 y=0 z=0
E1 N1 N2 w=1 h=0.035 nwinc={mesh[0]} nhinc={mesh[1]}
.external N1 N2
""" + tail


def case_b(mesh):
    top, tail = head("B: go-and-return bars, far end shorted", 1.0)
    return top + f"""N1 x=0 y=0 z=0
N2 x=10 y=0 z=0
N3 x=0 y=5 z=0
N4 x=10 y=5 z=0
E1 N1 N2 w=1 h=0.035 nwinc={mesh[0]} nhinc={mesh[1]}
E2 N3 N4 w=1 h=0.035 nwinc={mesh[0]} nhinc={mesh[1]}
.equiv N2 N4
.external N1 N3
""" + tail


C_W, C_T, C_GAP, C_FREQ, D_FREQ = 10.0, 0.035, 0.127, 1e8, 1e9


def skin_depth(f):
    return math.sqrt(RHO_CU / (math.pi * f * MU0))


def case_c(mesh, length, freq=C_FREQ):
    top, tail = head(f"C: parallel-plate loop, {length} mm, {freq:g} Hz", freq)
    z_top = C_GAP + C_T  # centre-to-centre spacing of the strips
    return top + f"""N1 x=0 y=0 z=0
N2 x={length} y=0 z=0
N3 x=0 y=0 z={z_top:g}
N4 x={length} y=0 z={z_top:g}
E1 N1 N2 w={C_W} h={C_T} nwinc={mesh[0]} nhinc={mesh[1]} rw=2 rh=2
E2 N3 N4 w={C_W} h={C_T} nwinc={mesh[0]} nhinc={mesh[1]} rw=2 rh=2
.equiv N2 N4
.external N1 N3
""" + tail


def grover_bar_self(l, w, t):
    """Partial self-inductance of a straight rectangular bar (Grover), SI units."""
    return MU0 * l / (2 * math.pi) * (math.log(2 * l / (w + t)) + 0.5 + 0.2235 * (w + t) / l)


def grover_mutual(l, d):
    """Mutual inductance of two parallel filaments of length l at distance d (Grover), SI units."""
    return MU0 * l / (2 * math.pi) * (math.log(l / d + math.sqrt(1 + (l / d) ** 2))
                                      - math.sqrt(1 + (d / l) ** 2) + d / l)


def palmer_plate_l_per_m(w, h):
    """Inductance per metre of a parallel-plate pair with Palmer's fringing correction (thin plates)."""
    return MU0 * h / (w * (1 + h / (math.pi * w) * (1 + math.log(2 * math.pi * w / h))))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=ROOT / "results/gan/fasthenry-known-answer.json")
    args = parser.parse_args()
    if not FH_BIN.is_file():
        raise SystemExit(f"missing {FH_BIN}; build it as described in docs/build.md")
    run_root = ROOT / "runs" / ("fasthenry-ka-" + uuid.uuid4().hex)
    meshes = {"A": [(1, 1), (3, 3), (7, 5)], "B": [(1, 1), (3, 3), (7, 5)], "C": [(9, 3), (19, 5), (39, 9)]}
    results = {}

    def inductance(z, f):
        return z.imag / (2 * math.pi * f)

    # A
    ref_a = grover_bar_self(10e-3, 1e-3, 35e-6)
    vals = []
    for m in meshes["A"]:
        z, _ = run_fasthenry(case_a(m), run_root / f"A_{m[0]}x{m[1]}")
        vals.append(inductance(z[1.0], 1.0))
    results["A"] = {"reference_H": ref_a, "reference": "Grover, rectangular bar, l=10 mm, w=1 mm, t=35 um",
                    "meshes": meshes["A"], "values_H": vals}
    # B
    ref_b = 2 * (grover_bar_self(10e-3, 1e-3, 35e-6) - grover_mutual(10e-3, 5e-3))
    vals = []
    for m in meshes["B"]:
        z, _ = run_fasthenry(case_b(m), run_root / f"B_{m[0]}x{m[1]}")
        vals.append(inductance(z[1.0], 1.0))
    results["B"] = {"reference_H": ref_b,
                    "reference": "2 (L_self - M): Grover bar self-inductance and filament mutual at 5 mm",
                    "meshes": meshes["B"], "values_H": vals}
    # C
    ref_c = palmer_plate_l_per_m(C_W * 1e-3, C_GAP * 1e-3)
    vals, detail = [], []
    for m in meshes["C"]:
        l20 = inductance(run_fasthenry(case_c(m, 20), run_root / f"C_{m[0]}x{m[1]}_20mm")[0][C_FREQ], C_FREQ)
        l10 = inductance(run_fasthenry(case_c(m, 10), run_root / f"C_{m[0]}x{m[1]}_10mm")[0][C_FREQ], C_FREQ)
        per_m = (l20 - l10) / 10e-3
        vals.append(per_m)
        detail.append({"mesh": m, "loop_20mm_H": l20, "loop_10mm_H": l10})
    results["C"] = {"reference_H_per_m": ref_c,
                    "reference": "mu0 h / w with Palmer fringing, w=10 mm, inner gap h=0.127 mm",
                    "ideal_no_fringing_H_per_m": MU0 * C_GAP / C_W,
                    "frequency_Hz": C_FREQ, "strip_thickness_mm": C_T,
                    "meshes": meshes["C"], "values_H_per_m": vals, "loops": detail}
    c_vals = vals
    # D (declared after C failed; see docstring)
    vals, detail = [], []
    for m in meshes["C"]:
        l20 = inductance(run_fasthenry(case_c(m, 20, D_FREQ), run_root / f"D_{m[0]}x{m[1]}_20mm")[0][D_FREQ], D_FREQ)
        l10 = inductance(run_fasthenry(case_c(m, 10, D_FREQ), run_root / f"D_{m[0]}x{m[1]}_10mm")[0][D_FREQ], D_FREQ)
        vals.append((l20 - l10) / 10e-3)
        detail.append({"mesh": m, "loop_20mm_H": l20, "loop_10mm_H": l10})
    d1, d2 = skin_depth(D_FREQ), skin_depth(C_FREQ)
    results["D_absolute"] = {
        "reference_H_per_m": palmer_plate_l_per_m(C_W * 1e-3, C_GAP * 1e-3 + d1),
        "reference": "Palmer with the gap increased by one skin depth (internal inductance of both plates)",
        "skin_depth_m": d1, "frequency_Hz": D_FREQ, "meshes": meshes["C"], "values_H_per_m": vals, "loops": detail}
    results["D_ratio"] = {
        "reference_H_per_m": (C_GAP * 1e-3 + d1) / (C_GAP * 1e-3 + d2),
        "reference": "(h + delta_1GHz) / (h + delta_100MHz); dimensionless, stored in the same field",
        "skin_depths_m": {"1GHz": d1, "100MHz": d2}, "meshes": meshes["C"],
        "values_H_per_m": [a / b for a, b in zip(vals, c_vals)]}
    results["C"]["diagnosis_after_failure"] = {
        "skin_corrected_reference_H_per_m": palmer_plate_l_per_m(C_W * 1e-3, C_GAP * 1e-3 + d2),
        "skin_depth_m": d2,
        "note": "added after the declared check failed; not an acceptance result"}

    outcome = {}
    for key, r in results.items():
        v = r.get("values_H") or r["values_H_per_m"]
        ref = r.get("reference_H") or r["reference_H_per_m"]
        mesh_change = abs(v[-1] / v[-2] - 1)
        err = v[-1] / ref - 1
        r.update(finest_relative_error=err, tolerance=TOL[key], mesh_change_two_finest=mesh_change,
                 mesh_tolerance=MESH_TOLERANCE,
                 outcome="pass" if abs(err) <= TOL[key] and mesh_change <= MESH_TOLERANCE else "fail")
        outcome[key] = r["outcome"]
    fh_commit = subprocess.run(["git", "-C", str(FH_DIR), "rev-parse", "HEAD"], capture_output=True, text=True).stdout.strip()
    report = {
        "schema": "fasthenry-known-answer/1",
        "purpose": "qualify the inductance extraction tool before EPC9097 layout extraction (G3)",
        "tool": {"name": "FastHenry 3.0.1", "source": "https://github.com/ediloren/FastHenry2 (master)",
                 "commit": fh_commit, "binary_sha256": hashlib.sha256(FH_BIN.read_bytes()).hexdigest(),
                 "build": "./config x64; make fasthenry CFLAGS='-O -DFOUR -m64 -fcommon' (gcc 13.3, Ubuntu 24.04 WSL)",
                 "licence": "MIT 1994: internal, noncommercial use; redistribution prohibited without MIT's consent"},
        "declared_before_first_run": {"tolerances": TOL, "mesh_tolerance": MESH_TOLERANCE},
        "cases": results,
        "outcome": outcome,
        "evidence_directory": str(run_root.relative_to(ROOT)),
        "evaluator_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps({k: {"ref": r.get("reference_H") or r["reference_H_per_m"],
                          "values": r.get("values_H") or r["values_H_per_m"],
                          "err": round(r["finest_relative_error"], 5), "mesh_change": round(r["mesh_change_two_finest"], 5),
                          "outcome": r["outcome"]} for k, r in results.items()}, indent=1))
    return 0 if all(o == "pass" for o in outcome.values()) else 2


if __name__ == "__main__":
    raise SystemExit(main())
